# Generated by Django 4.0.2 on 2022-05-11 06:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('amount', models.IntegerField(default=1000, help_text='1000 means 10$', verbose_name='amount to be charged')),
                ('duration', models.IntegerField(default=30, verbose_name='duration in days')),
                ('currency', models.CharField(default='usd', max_length=3, verbose_name='amount currency')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_intent', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('payment_intent.created', 'PAYMENT_INTENT_CREATED'), ('charge.succeeded', 'CHARGE_SUCCEEDED'), ('payment_intent.succeeded', 'PAYMENT_INTENT_SUCCEEDED'), ('payment_intent.processing', 'PAYMENT_INTENT_PROCESSING'), ('payment_intent.payment_failed', 'PAYMENT_INTENT_FAILED'), ('unhandled_event', 'UNHANDLED_EVENT')], default='unhandled_event', max_length=32, verbose_name='payment event type')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='amount to be charged')),
                ('currency', models.CharField(blank=True, max_length=3, null=True, verbose_name='amount currency')),
                ('response', models.JSONField(default=dict, verbose_name='payment event response')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('payment_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_events', to='payments.paymentplan')),
            ],
        ),
    ]
